# Generated by Django 4.1 on 2022-10-27 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_comment_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='updated_at',
        ),
    ]
