# Generated by Django 4.1 on 2022-10-28 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 6, 32, 56, 261058, tzinfo=datetime.timezone.utc)),
        ),
    ]
