# Generated by Django 4.1 on 2022-10-27 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UMKM_Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default=None, max_length=255)),
                ('description', models.TextField(default='')),
                ('umkm_url', models.URLField(default='')),
                ('number', models.CharField(default='', max_length=13)),
                ('rating_total', models.FloatField(default=5.0)),
                ('rating_count', models.IntegerField(default=1)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='general.umkm')),
            ],
        ),
    ]
