# Generated by Django 4.1 on 2022-10-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_alter_umkm_shop_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umkm_shop',
            name='shop_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
