# Generated by Django 4.1 on 2022-10-28 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0007_alter_umkm_shop_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umkm_shop',
            name='owner',
        ),
    ]
