# Generated by Django 4.1 on 2022-10-29 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showcase', '0008_remove_umkm_shop_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('umkm_url', models.URLField(default='')),
                ('number', models.CharField(default='', max_length=13)),
                ('rating_total', models.FloatField(default=5.0)),
                ('rating_count', models.IntegerField(default=1)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UMKM_Shop',
        ),
    ]
