# Generated by Django 4.1 on 2022-11-01 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
        ('showcase', '0009_shop_delete_umkm_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='general.umkm'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='rating_total',
            field=models.IntegerField(default=5),
        ),
    ]
