# Generated by Django 4.1 on 2022-11-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0010_shop_image_alter_shop_owner_alter_shop_rating_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[('OTH', 'Other'), ('FNB', 'Food and Beverages'), ('FSH', 'Fashion'), ('AGR', 'Agriculture'), ('ELE', 'Electronic'), ('FUR', 'Furniture'), ('SER', 'Service')], default='OTH', max_length=3),
        ),
    ]
