# Generated by Django 4.1 on 2022-11-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0011_shop_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[('SEL', '-----SELECT-----'), ('FNB', 'Food and Beverages'), ('FSH', 'Fashion'), ('AGR', 'Agriculture'), ('ELE', 'Electronic'), ('FUR', 'Furniture'), ('SER', 'Service'), ('OTH', 'Other')], default='OTH', max_length=3),
        ),
    ]
