# Generated by Django 4.1 on 2022-11-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0011_shop_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[('SEL', '-----SELECT-----'), ('Food and Beverages', 'Food and Beverages'), ('Fashion', 'Fashion'), ('Agriculture', 'Agriculture'), ('Electronic', 'Electronic'), ('Furniture', 'Furniture'), ('Service', 'Service'), ('Other', 'Other')], default='other', max_length=18),
        ),
    ]
