# Generated by Django 4.1 on 2022-10-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrolan', '0002_alter_diskusi_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diskusi',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
