# Generated by Django 4.1 on 2022-10-26 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaLomba', models.TextField()),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cekPemilihan', models.BooleanField(default=False)),
                ('lomba', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lomba.lomba')),
                ('pemilih', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='general.customer')),
            ],
        ),
        migrations.CreateModel(
            name='DetailLomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailKeterangan', models.TextField()),
                ('lomba', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lomba.lomba')),
                ('peserta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='general.umkm')),
            ],
        ),
    ]
