# Generated by Django 4.1 on 2022-10-26 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
        ('lomba', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='cekPemilihan',
        ),
        migrations.AlterField(
            model_name='detaillomba',
            name='lomba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lomba.lomba'),
        ),
        migrations.AlterField(
            model_name='detaillomba',
            name='peserta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.umkm'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='lomba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lomba.lomba'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='pemilih',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.customer'),
        ),
    ]
