# Generated by Django 4.1 on 2022-10-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lomba', '0002_remove_voting_cekpemilihan_alter_detaillomba_lomba_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detaillomba',
            name='jumlahVote',
            field=models.IntegerField(default=0),
        ),
    ]
