# Generated by Django 4.1 on 2022-10-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lomba', '0004_alter_detaillomba_peserta_alter_voting_pemilih'),
    ]

    operations = [
        migrations.AddField(
            model_name='detaillomba',
            name='namaKarya',
            field=models.CharField(default='tesdoang', max_length=50),
        ),
        migrations.AddField(
            model_name='detaillomba',
            name='situsKarya',
            field=models.TextField(default='tesdoang'),
        ),
        migrations.AddField(
            model_name='lomba',
            name='tanggal',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='detaillomba',
            name='detailKeterangan',
            field=models.TextField(default='tesdoang'),
        ),
    ]
