# Generated by Django 4.1 on 2022-10-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lomba', '0005_detaillomba_namakarya_detaillomba_situskarya_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaillomba',
            name='detailKeterangan',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detaillomba',
            name='namaKarya',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='detaillomba',
            name='situsKarya',
            field=models.TextField(),
        ),
    ]
