# Generated by Django 4.1 on 2022-10-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lomba', '0006_alter_detaillomba_detailketerangan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lomba',
            name='berjalan',
            field=models.BooleanField(default=True),
        ),
    ]
